### ISSUE TITLE
No file name for source code & TypeError

### ISSUE THREAD

**Issue by luqmanarifin** [h0tsh0tt/Beautiful-Scrape#1]
Grabbed files have no file type such as .cpp or .java or .pas.

And this error occured in the middle of scrapping.

```
Traceback (most recent call last):
  File "scrape.py", line 37, in <module>
    problem_name = var[2].a['href'].split('/')[4]
TypeError: 'NoneType' object has no attribute '__getitem__'
```

**Comment by h0tsh0tt** [comment]
Thank you for reporting the issue!

I will be adding the file type feature soon. 
Can you more elaborate more on the error like from which profile were u scraping out code and what was the last code that the script scraped before the error came , so that I can look into it.

**Comment by shrishtirajora** [comment]
Thank you for reporting the issue!

The bug has been fixed now you won't be getting the error!
